### ISSUE TITLE
Реализовать систему поиска в чатах 

### ISSUE THREAD

**Issue by catttrap** [codepandoradev/nft-marketplace-api#159]
## Описание

Необходимо реализовать поиск конкретного чата по никнейму пользователя. Дизайна под это еще нет, но будет как только я ткну дизайнера+nчасов

#### Пункты в ТЗ

- Их, конечно же, там нет :)

**Comment by GentleEnvy** [comment]
Не совсем понятно что конкретно нужно. Сейчас есть endpoint **GET /messenger/direct/\<interlocutor\>/messages/**, где в _\<interlocutor\>_ указывается _id_ пользователя и возвращается список сообщений с ним.
Я пока сделаю только поиск пользователей по _username_. Если этого достаточно, закроем issue, если нет - я думаю лучше дождаться дизайна и по нему решить что ещё надо

**Comment by catttrap** [comment]
Дизайн:

![IMG_20221228_160012_487.jpg](https://user-images.githubusercontent.com/86266201/209816279-4f878f42-ac06-42de-af2f-db6075b28733.jpg)

Поиск пока что только по юзернейму, так что да. Как сделаешь его - можешь закрывать исуху
