### ISSUE TITLE
Добавить поля для редактирования пользователя в соответствии с Figma 

### ISSUE THREAD

**Issue by catttrap** [codepandoradev/nft-marketplace-api#208]
### Блокирует

- [x] #212

## Описание

<img width="394" alt="image" src="https://user-images.githubusercontent.com/86266201/212470384-c6e27033-7e46-448b-8340-b6f0d3e164b6.png">

Возможно, где-то есть отдельная страница редактирования пользователя, но в фигме я ее не нашла, напишу Руслану по этому поводу

**Comment by GentleEnvy** [comment]
Это в самом низу, в разделе NEW -> Настройки
![image](https://user-images.githubusercontent.com/58393514/212499026-8ab0f839-519e-4709-94fc-866958fcb521.png)


Ещё Эрик сказал, что поля будут немного отличаться - email не будет и ещё что-то. Уточни это

**Comment by catttrap** [comment]
Поняла, спасибо. С Эриком сегодня должны созвониться, если все будет по плану, дам инфу сегодня

**Comment by GentleEnvy** [comment]
Видимо не по плану ..
В общем я добавил display name и bio. Из того что на дизайне, нет email, twitter, website и в wallets можно только 1 кошелёк установить.
Пока закрою, чтобы на stage улетело. Если на бетку нужно больше, напиши что конкретно и сделай reopen
