### ISSUE TITLE
Сделать систему и страницу поиска

### ISSUE THREAD

**Issue by GentleEnvy** [codepandoradev/nft-marketplace-api#222]

**Comment by GentleEnvy** [comment]
Поиска чего ?..

@catttrap

**Comment by catttrap** [comment]
Система поиска:
1) Поиск по nft-шкам - поиск осуществляется по названиям nft-шек. фильтрация и сортировка по цене, фильтрация по "аукционности", фильтрация по популярности (сделаем заглушку)
2) Поиск по пользователям - поиск осуществляется по юзернеймам пользователей. Фильтрация и сортировка отсутствуют
3) Поиск по коллекциям - Поиск осуществляется по названиям коллекций. Фильтрация по блокчейнам, фильтрация по популярности (сделаем заглушку)
4) Общий поиск - поиск осуществляется по названиям коллекций, nft-шек (при поиске выпадают разделы, в которых что-то нашлось и то, что нашлось.), юзернеймам продавцов (авторов). Также при поиске выпадают ключевые слова (Также юзернеймы авторов, названия коллекций), которые можно выбрать и вас перекинет на страницу пользователя, либо на страницу коллекции.
