### ISSUE TITLE
Перенести stage на https

### ISSUE THREAD

**Issue by catttrap** [codepandoradev/nft-marketplace-api#234]

**Comment by GentleEnvy** [comment]
Надо брать SSL на поддомен, а это дорого (

**Comment by catttrap** [comment]
Сколько?

**Comment by GentleEnvy** [comment]
Не знаю, надо зайти в рег ру, а там нужен код из смс, а это я делал через Эрика, который сейчас вряд ли мне достаточно быстро ответит.
Короче я не думаю, что это приоритетная задача сейчас, лучше после бетки
